uploads = []

[[generated]]
id = "2Ko1SfRFavhsyDUHW2w92"
uri = "file://artifacts/gps-video-capture/assets/images/icon.png"
type = "image"
title = "gps-video-capture-app-icon"

[[outputs]]
id = "iWe9wYbRhEA43vSGK-PAC"
uri = "file://artifacts/gps-video-capture/APP_STORE_CHECKLIST.md"
type = "text"
title = "iOS App Store Checklist"
